// ABOUTME: Experiments demo page showing creative explorations of UI patterns
// ABOUTME: Dropdown selector to choose exploration category, displays all experiments sorted by date

import type { Component } from "solid-js";
import { createMemo, createSignal, For, Show } from "solid-js";
import Section from "../components/Section";
import { Combobox, type ComboboxOption } from "../components/ui/Combobox";
import { cardSurfaceFlat } from "../styles/containerStyles";

// This will be generated by pnpm generate:experiments
// For now, we'll handle the empty case gracefully
let primaryButtonExperiments: Array<{
  id: string;
  component: Component;
  metadata: { id: string; title: string; description?: string; date?: string };
}> = [];

let agentTopBarExperiments: Array<{
  id: string;
  component: Component;
  metadata: { id: string; title: string; description?: string; date?: string };
}> = [];

let headerTitleExperiments: Array<{
  id: string;
  component: Component;
  metadata: { id: string; title: string; description?: string; date?: string };
}> = [];

try {
  const experimentsModule = await import("../experiments");
  primaryButtonExperiments = experimentsModule.primaryButtonsExperiments || [];
  agentTopBarExperiments = experimentsModule.agentTopBarExperiments || [];
  headerTitleExperiments = experimentsModule.headerTitleExperiments || [];
} catch {
  // No experiments yet - that's okay!
}

// Define exploration categories
interface Exploration {
  id: string;
  name: string;
  description: string;
  experiments: Array<{
    id: string;
    component: Component;
    metadata: { id: string; title: string; description?: string; date?: string };
  }>;
}

const explorations: Exploration[] = [
  {
    id: "header-title",
    name: "Header Title",
    description:
      "Different approaches to displaying 'Birdhouse' with Bird + House icons that share a seamless gradient. Mobile-friendly designs that condense to icons only.",
    experiments: headerTitleExperiments,
  },
  {
    id: "agent-top-bar",
    name: "Agent Top Bar",
    description:
      "Compact header designs for agent cards. Each experiment shows a different approach to integrating the theme gradient while displaying agent metadata.",
    experiments: agentTopBarExperiments,
  },
  {
    id: "primary-buttons",
    name: "Primary Buttons",
    description:
      "Various gradient and styling approaches for primary buttons. Each experiment shows Primary, Secondary, and Tertiary button variants in different states.",
    experiments: primaryButtonExperiments,
  },
];

const ExperimentsDemo: Component = () => {
  // Create dropdown options from explorations
  const explorationOptions = createMemo((): ComboboxOption<string>[] => {
    return explorations
      .filter((exp) => exp.experiments.length > 0)
      .map((exp) => {
        // Find most recent experiment date
        const mostRecentDate = exp.experiments
          .map((e) => e.metadata.date)
          .filter((d): d is string => !!d)
          .sort()
          .reverse()[0];

        return {
          value: exp.id,
          label: exp.name,
          description: mostRecentDate
            ? `${exp.experiments.length} experiments • Last: ${mostRecentDate}`
            : `${exp.experiments.length} experiments`,
        };
      });
  });

  // Select the first exploration by default
  const [selectedExplorationId, setSelectedExplorationId] = createSignal<string | undefined>(
    explorations.find((exp) => exp.experiments.length > 0)?.id,
  );

  // Get the currently selected exploration
  const selectedExploration = createMemo(() => {
    const id = selectedExplorationId();
    return explorations.find((exp) => exp.id === id);
  });

  return (
    <div class="flex flex-col h-full">
      {/* Header */}
      <div class="px-4 py-3 border-b bg-surface-raised border-border flex-shrink-0">
        <div class="flex items-center justify-between mb-3">
          <h2 class="text-lg font-semibold text-heading">Experiments</h2>
          <p class="text-sm text-text-secondary hidden md:block">Creative explorations of UI patterns and styling</p>
        </div>

        {/* Exploration Selector */}
        <Show when={explorationOptions().length > 0}>
          <div class="max-w-2xl">
            <Combobox
              options={explorationOptions()}
              value={selectedExplorationId()}
              onSelect={(value) => setSelectedExplorationId(value)}
              placeholder="Select an exploration..."
            />
          </div>
        </Show>
      </div>

      {/* Content */}
      <div class="flex-1 overflow-y-auto p-8">
        <Show
          when={explorationOptions().length > 0}
          fallback={
            <div class={`p-8 text-center space-y-4 ${cardSurfaceFlat} rounded-lg`}>
              <p class="text-text-secondary">No experiments yet! Run the following to generate experiments:</p>
              <code class="block px-4 py-2 bg-surface-inset rounded text-sm text-accent font-mono">
                pnpm generate:experiments
              </code>
              <p class="text-xs text-text-muted">
                Experiments are located in <code class="text-accent">src/experiments/</code>
              </p>
            </div>
          }
        >
          <Show when={selectedExploration()} keyed>
            {(exploration) => (
              <Section title={exploration.name} description={exploration.description}>
                <div class="space-y-8">
                  <For each={exploration.experiments}>
                    {(experiment) => {
                      const ExperimentComponent = experiment.component;
                      return (
                        <div class={`space-y-4 p-6 ${cardSurfaceFlat} rounded-lg`}>
                          {/* Experiment Header */}
                          <div class="space-y-1">
                            <div class="flex items-baseline gap-3">
                              <span class="text-xs font-mono text-text-muted">#{experiment.metadata.id}</span>
                              <h3 class="text-lg font-semibold text-heading">{experiment.metadata.title}</h3>
                              <Show when={experiment.metadata.date}>
                                <span class="text-xs text-text-muted ml-auto">{experiment.metadata.date}</span>
                              </Show>
                            </div>
                            <Show when={experiment.metadata.description}>
                              <p class="text-sm text-text-secondary">{experiment.metadata.description}</p>
                            </Show>
                          </div>

                          {/* Experiment Content */}
                          <div class="pt-2">
                            <ExperimentComponent />
                          </div>
                        </div>
                      );
                    }}
                  </For>
                </div>
              </Section>
            )}
          </Show>
        </Show>
      </div>
    </div>
  );
};

export default ExperimentsDemo;
